### ISSUE TITLE
Could not find a version of package jacopovalanzano/php-captcha matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired  stability.  

### ISSUE THREAD

**Issue by Artemixed** [jacopovalanzano/php-captcha#1]
Heyo! I found this project and wanted to give it a spin! Sadly I can't get it to work.  

this is what my composer lock file looks like, i've both tried it with minium-stability set to "stable" and "dev"
```
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "dev",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": [],
    "plugin-api-version": "2.1.0"
```

**Comment by Artemixed** [comment]
I got it to work with the following require command! 

```composer require jacopovalanzano/php-captcha:dev-main``` 

I would like to request proper versioning or to change the commands on the page to reflect the one I had to use.

**Comment by jacopovalanzano** [comment]
Thank you. Will fix asap.

Jacopo
